### ISSUE TITLE
Needs to have federal holiday values put in for each month

### ISSUE THREAD

**Issue by 2hands10fingers** [2hands10fingers/Time#1]
Edit each month object and add holiday values. January() and February() are good examples.

**Comment by BenCoden** [comment]
ill add these holidays 

 New Year's Day |  January 1st
 Birthday of Martin Luther King, Jr. |  January 15th
 Washington's Birthday (President's Day) |  February 19th
 Memorial Day | May 28th
 Independence Day | July 4th
 Labor Day |  September 3rd
 Columbus Day |  October 8th
 Veterans Day |  November 12th *
 Thanksgiving Day |  November 22nd
 Christmas Day |  December 25th

**Comment by 2hands10fingers** [comment]
Awesome! Thanks so much!
